import {
  AddIcon,
  AnalyticsOutline,
  AnalyticsSolid,
  ArrowLeft,
  Breadcrumb,
  Calendar,
  CloseIcon,
  DeleteOutline,
  DeleteSolid,
  Logo,
  MailOpenOutline,
  MailOpenSolid,
  MailSolid,
  PenIcon,
  SearchIcon,
  SendOutline,
  SendSolid,
  SpamOutline,
  SpamSolid,
} from "../SVG";

export const IconType = {
  SEARCH: SearchIcon,
  CLOSE: CloseIcon,
  MAIL_OPEN_OUTLINE: MailOpenOutline,
  MAIL_OPEN_SOLID: MailOpenSolid,
  SEND_OUTLINE: SendOutline,
  SEND_SOLID: SendSolid,
  DELETE_OUTLINE: DeleteOutline,
  DELETE_SOLID: DeleteSolid,
  ANALYTICS_OUTLINE: AnalyticsOutline,
  ANALYTICS_SOLID: AnalyticsSolid,
  PEN: PenIcon,
  ADD: AddIcon,
  ARROW_LEFT: ArrowLeft,
  CALENDER: Calendar,
  SPAM_OUTLINE: SpamOutline,
  SPAM_SOLID: SpamSolid,
  MAIL_SOLID: MailSolid,
  BREADCRUMB: Breadcrumb,
  LOGO: Logo,
};
