import {
  AddIcon,
  AnalyticsOutline,
  AnalyticsSolid,
  ArrowLeft,
  Calendar,
  CloseIcon,
  DeleteOutline,
  DeleteSolid,
  MailOpenOutline,
  MailOpenSolid,
  PenIcon,
  SearchIcon,
  SendOutline,
  SendSolid,
} from "../SVG";

export const IconType = {
  SEARCH: SearchIcon,
  CLOSE: CloseIcon,
  MAIL_OPEN_OUTLINE: MailOpenOutline,
  MAIL_OPEN_SOLID: MailOpenSolid,
  SEND_OUTLINE: SendOutline,
  SEND_SOLID: SendSolid,
  DELETE_OUTLINE: DeleteOutline,
  DELETE_SOLID: DeleteSolid,
  ANALYTICS_OUTLINE: AnalyticsOutline,
  ANALYTICS_SOLID: AnalyticsSolid,
  PEN: PenIcon,
  ADD: AddIcon,
  ARROW_LEFT: ArrowLeft,
  CALENDER: Calendar,
};
